name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npx @11ty/eleventy

      - name: Deploy to DreamHost
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DREAMHOST_HOST }}
          username: ${{ secrets.DREAMHOST_USERNAME }}
          password: ${{ secrets.DREAMHOST_PASSWORD }}
          source: "public/*"
          target: "/home/${{ secrets.DREAMHOST_USERNAME }}/your-website-directory"
